version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /var/www/backend
    depends_on:
      - pgsql
      - frontend
      - redis
    networks:
      - app
    container_name: app

  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "${APP_NODE_PORT:-3000}:3000"
    volumes:
      - ./frontend:/var/www/frontend
      - /var/www/frontend/node_modules
    networks:
      - app
    container_name: app_node

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "${APP_NGINX_PORT:-80}:80"
    volumes:
      - type: bind
        source: ./backend
        target: /var/www/backend
      - type: bind
        source: ./.docker/nginx/conf.d
        target: /etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app
    container_name: app_nginx

  pgsql:
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    restart: always
    ports:
      - "${APP_POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${APP_POSTGRES_DB:-example_db}"
      POSTGRES_USER: "${APP_POSTGRES_USER:-root}"
      POSTGRES_PASSWORD: "${APP_POSTGRES_PASSWORD:-password}"
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    networks:
      - app
    volumes:
      - type: bind
        source: ./.docker/tmp/pgsql
        target: /var/lib/postgresql/data
    container_name: app_pgsql

  mailpit:
    build:
      context: .
      dockerfile: .docker/mailpit/Dockerfile
    ports:
      - '${APP_MAILPIT_PORT:-1025}:1025'
      - '${APP_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - app
    container_name: app_mailpit

  redis:
    build:
      context: .
      dockerfile: .docker/redis/Dockerfile
    ports:
      - '${APP_REDIS_PORT:-6379}:6379'
    volumes:
      - type: bind
        source: ./.docker/tmp/redis
        target: /data
    networks:
      - app
    container_name: app_redis

networks:
  app:
    driver: bridge